// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT user_id, revoked_at from refresh_tokens where token = $1
`

type GetUserFromTokenRow struct {
	UserID    uuid.UUID
	RevokedAt sql.NullTime
}

func (q *Queries) GetUserFromToken(ctx context.Context, token string) (GetUserFromTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, token)
	var i GetUserFromTokenRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES (
  $1,Now(),Now(), $2, $3
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type InsertTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, insertToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens SET updated_at = Now(), revoked_at = Now() where token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
