// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hash_password)
VALUES (
    gen_random_uuid(),Now(),Now(), $1, $2
)
RETURNING id, created_at, updated_at, email, hash_password, is_chirpy_red
`

type CreateUserParams struct {
	Email        string
	HashPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserWithEmail = `-- name: GetUserWithEmail :one
SELECT id, created_at, updated_at, email, hash_password, is_chirpy_red FROM users where email = $1
`

func (q *Queries) GetUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const setUserRed = `-- name: SetUserRed :exec
UPDATE users SET is_chirpy_red = true, updated_at = Now() where id = $1
`

func (q *Queries) SetUserRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setUserRed, id)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2, hash_password = $3, updated_at = Now() where id = $1
`

type UpdateUserEmailParams struct {
	ID           uuid.UUID
	Email        string
	HashPassword string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.ID, arg.Email, arg.HashPassword)
	return err
}
